services:
  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - mern-network

  client:
    build: ./client
    container_name: client
    ports:
      - "5173:5173"
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev -- --host
    environment:
    - CHOKIDAR_USEPOLLING=true
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge